### ISSUE TITLE
Update plans?

### ISSUE THREAD

**Issue by The-HAX0R-31337** [Skilles/SpokenWord#1]
Do you plan on updating this to current versions?

**Comment by Skilles** [comment]
Sure, I'll get around to it sometime this year

**Comment by The-HAX0R-31337** [comment]
Is there anything I can do to help with updating? I don't know how to code or anything but I'd be happy to be a beta tester or something.

**Comment by Skilles** [comment]
Yeah for sure there's a lot to test. With a complete rewrite, adding a bunch new features and with life going on its taking longer than I anticipated. Once I have a few more features added I'll have a beta build ready for 1.19+

**Comment by Skilles** [comment]
Version 2.0 for Minecraft 1.20.1 and 1.20.2 is now released
